/*
 * Throwable----> Super class of all the exceptions
 * 	
 * 	Throwable :
 * 			- Exception class(Can be handled)
 * 						- Checked
 * 								- IOException
 * 								- SQLException
 * 						- Unchecked
 * 								- All Runtime exceptions like : 
 * 										- ArithmaticException
 * 										- ArrayIndexOutOfBoundsException
 * 										- FileNotFoundException
 * 			- Error class(Can't be handled)
 * 
 * 
 * 
 * 
 * - We can have multiple catch blocks for one try..Following is the example
 * 		- We're using 2 catch blocks to handle exceptions of 2 types
 * 			which are ArithmaticException and ArrayIndexOutofBoundsException
 * 
 * 
 * 
 */



//DemoForCheckedException

package com.telusko.exceptionHandling;

public class CheckedExceptionDemo {

	public static void main(String[] args) {
		
		
		int i, j, k=0;
		i = 8;
		j = 0;
		int a [] = new int [4];
		
		try {
			k = i/j;							//for arithmetic exception
			
			for(int c = 0; c <=4; c++) {
				a[c] = c+1;
			}
			for(int value : a) {
				System.out.println(value);
			}
			
		}
		
		catch(ArithmeticException e){						//Or we can write just "Exception e" as well in the catch block
			System.out.println("Cannot divide by zero");		//Unchecked exception
		}
		
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("Maximum number of values is 4");	//Unchecked exception
		}
		
		
		//following block cannot be used as first catch block before 'ae' and 'e'
		catch(Exception e) {							//Used when type of exception is not known
			System.out.println("Unknown exception");
		}
		
		
		System.out.println(k);
		
	}

}



